# h2 console is available at http://localhost:8080/h2-console

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  info:
    env:
      enabled: true
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, info, env, beans"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true

info:
  app:
    name: Spring Library Application
    description: This is my second spring boot application
    version: 1.0.0