spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  sql:
    init:
      mode: never # don't use data.sql

management:
  info:
    env:
      enabled: true
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, info, env, beans"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true
